### ISSUE TITLE
Add "copy to clipboard" button in newdle creation success page

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#132]
![image](https://user-images.githubusercontent.com/2699/67392853-95023380-f5a1-11e9-8652-6fbd976c6900.png)

**Comment by ThiefMaster** [comment]
Selecting all the text when clicking it so you can just CTRL+C it would already be great! But since the API to write to the clipboard in modern browsers is pretty decent having a button for it as well makes sense.

**Comment by pferreir** [comment]
It's actually [ultra-simple](https://github.com/indico/indico/pull/4057/files#diff-3471c3545cc248a840158c9ee57e4c56R27).

**Comment by skbro** [comment]
I would like to work on this issue.
So, I need to add the copy button component to CreationSuccessPage.js using Clipboard API?

**Comment by ThiefMaster** [comment]
Hi, great to see you are interested in contribution to newdle!

Of course this should be done in a way that looks nice - for example, you might want to make it clear that clicking it copies (could be an icon). But the basic functionality is indeed pretty straightforward - adding an icon button inside the area, and copying the text when you click it.

Please do test your change though before opening a pull request! You should be able to run newdle locally fine by setting `SKIP_LOGIN = True` and otherwise just following the guide in the README.

Feel free to ping us in our IRC channel #indico on freenode if you have any other questions.
