### ISSUE TITLE
Improve responsiveness of newdle summary page

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#134]
![image](https://user-images.githubusercontent.com/179599/90772076-715c6680-e2f4-11ea-903b-1ad1cd0bf8d2.png)

**Comment by hugonxc** [comment]
Can I work on this one?

**Comment by ThiefMaster** [comment]
sure!

**Comment by hugonxc** [comment]
Hey there! I have a few questions.
First one: I got and runtime error when I click on login button. I follow all steps on README, but I still got:
``
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
``
And: I have some default user to logging on devel server?
Thanks

**Comment by ThiefMaster** [comment]
You need to add this to your `newdle.cfg`:

    SECRET_KEY = 'some random garbage here'

Also, you want `SKIP_LOGIN = True` so you are logged in as a dummy user when you click the login button.

**Comment by hugonxc** [comment]
Awesome!

**Comment by ThiefMaster** [comment]
I just added a commit to master that puts useful developer defaults in the config when creating it (the makefile won't be used for non-development setups anyway).
