### ISSUE TITLE
Implement i18n

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#136]
Still to see whether we want to go for an Indico-like solution (with [react-jsx-i18n](https://github.com/indico/react-jsx-i18n)) or to try out something like [react-intl](https://github.com/formatjs/react-intl).

**Comment by ThiefMaster** [comment]
Lingui might be interesting - very similar to react-jsx-i18n: https://lingui.js.org/tutorials/react.html

**Comment by Tautorn** [comment]
I will take it, if still available

**Comment by ThiefMaster** [comment]
Sure - maybe you could start with a single component so we can have a look?

I'd propose lingui (especially since it has a nice integration with babel macros which we already use anyway). The fact that it uses English strings as the source language is quite nice as well (I *really* do not want message id like "newdle.create.button.label" for a "Create newdle!" button).

**Comment by Tautorn** [comment]
Sure, I will create a simple component using Lingui.

**Comment by ThiefMaster** [comment]
@Tautorn How is it going? If you need any help feel free to ask here or in our [IRC channel](https://webchat.freenode.net/#indico).

**Comment by PatriciaMaPe** [comment]
I would like to do this

**Comment by ThiefMaster** [comment]
Sure! Please see my previous comment from October 2019 on some suggestions how to best get started :)
