### ISSUE TITLE
Edit newdle / add new slots after creation

### ISSUE THREAD

**Issue by noggin143** [indico/newdle#185]
When a Newdle is created, the host sets a set of slots which can be selected by the potential participants.

It would be useful to also be able to add further slots after the Newdle has been created. Typical use cases is where many participants would not be able to make the initial proposals and the meeting organiser would like to add further options but still retain the other options in a single poll if not all the potential participants have participated.

If it would also be possible to send an update to those who had responded to the Newdle that new slots have been made available, this would be very helpful.

**Comment by ThiefMaster** [comment]
*Copying my comment from the duplicate issue I had opened yesterday*


Currently there is no way to make any changes to a newdle after creating it, which is not great if you later realize that you need to change/add timeslots. We should allow editing those.

TBD what to do with existing answers. We could leave them as they are, and leave it up to the organizer to contact participants to update their answers after adding timeslots. In case of timeslot removal we have to check if the presence of answers for deleted timeslots is a problem; in that case we could purge them from all participants.

---

I would not do anything related to the list of participants in this task, since removing anyone would be confusing (they'd get an error when following the link in the email), and adding new ones is not really important since there's always the generic link that can be used to respond to the newdle.

**Comment by pkoppenb** [comment]
I just created a newdle and realised I failed to invite someone. It's annoying that I have to start a fresh one and can't just add someone.

**Comment by ThiefMaster** [comment]
You can always send the person the non-personalized newdle link - no need to start from scratch!

**Comment by pkoppenb** [comment]
Thanks. I started a new one anyway as I'd like things to be clean. But now I can't even delete the first failed attempt.
