### ISSUE TITLE
Use GitHub actions for CI

### ISSUE THREAD

**Issue by ThiefMaster** [indico/newdle#207]
Some stuff can probably be copied from the [Indico CI config](https://github.com/indico/indico/blob/master/.github/workflows/ci.yml)

**Comment by ParthS007** [comment]
I want to work on this one. :)

**Comment by ParthS007** [comment]
@ThiefMaster GH-Actions CI is running fine except `make test` and is specifically failing in Pytests which is most probably related to setting up of the database and I suspect this is due to the `newdle.cfg` not being created.

Here's the log to one of the previous jobs. -> [Link](https://github.com/ParthS007/newdle/runs/1117761642?check_suite_focus=true)

**Comment by ThiefMaster** [comment]
I don't think we rely on a newdle.cfg in tests (`make` creates it btw), the prorlbme is probably the hardcoded `TEST_DATABASE_URI = 'postgresql:///newdle_tests'` in `conftest.py`.

try replacing it with this:

    os.environ.get('NEWDLE_TEST_DATABASE_URI', 'postgresql:///newdle_tests')

**Comment by ParthS007** [comment]
Do we want to run in `python 3.8` only?
