### ISSUE TITLE
Create basic project site

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#214]
Should include:
 * Project description
 * Main features
 * Link to install instructions

**Comment by ParthS007** [comment]
Do we have any preference for the theme(like Jekyll or something similar)?

**Comment by ThiefMaster** [comment]
I don't think so... something that works out of the box with GH pages would be great though!

**Comment by Caetan95** [comment]
Hey! I am new here. Michal told me about the sprint (I am not registered) and I would like to collaborate. I think I can try to do this part with GH pages.

**Comment by ThiefMaster** [comment]
Not sure if @ParthS007 started with it already, or if you two may want to work together on it (not sure how to best split it on two people though). Best to check with him directly :)

**Comment by Caetan95** [comment]
I have talked with @ParthS007 and he didn't start it yet, so I can deal with this issue :)

**Comment by pferreir** [comment]
Guys, thanks for your interest in this. I just want to add that we don't need anything very complicated at this point: just something which is easy to update and which doesn't look too bad.

**Comment by Caetan95** [comment]
Yeap, pretty and simple

**Comment by Caetan95** [comment]
How can I find the Link to install instructions?

**Comment by ThiefMaster** [comment]
It's in the README of the project itself. But I don't think you need to install newdle for this task..

**Comment by pferreir** [comment]
> It's in the README of the project itself. But I don't think you need to install newdle for this task..

The ticket does mention he needs to link to the install instructions, though 😉

**Comment by Caetan95** [comment]
> > It's in the README of the project itself. But I don't think you need to install newdle for this task..
> 
> The ticket does mention he needs to link to the install instructions, though wink

yeap, that's why I asked haha I understand that install instructions are just the Development section of the README, just to be sure

**Comment by Caetan95** [comment]
I'm having a problem to make the github page reachable. As far as I know, to be able to make a webpage with GH I have to create a repo called "owner_name.github.io", but of course is not possible due to there is no newdle owner. I have several ideas to deal with it:

1. To copy the generated HTML code and create another webpage separated from github (ugly idea)
2. To create a newdle account in github to have a newdle owner and be able to create the page (also ugly idea)
3. To include in https://getindico.io (indico's github page) a section for newdle

Any idea about what should I do?

This is the page I did, but is in my repo, so if it is necessary to update nobody can do it

[site](https://caetan95.github.io)

**Comment by ThiefMaster** [comment]
When we deploy it via a `gh-pages` branch in this repo, it'll be accessible via `https://getindico.io/newdle/` initially, and we can eventually just point `newdle.io` to it. Or we can use a completely separate repo for it (`newdle-site`) and do the same... No strong opinion.

**Comment by Caetan95** [comment]
could you close it @ThiefMaster? I forgot to put the `closes #` tag when I create the PR. So sorry for that
